import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { AnimatePresence, MotionConfig, motion } from 'motion/react'
import './App.css'

type EventItem = { id: number; title: string; category: string; date: string; venue: string; host: string; attendees: number; image: string }
type Account = { name: string; email: string; department: string; role: string; reminders: boolean; announcements: boolean }
const seedEvents: EventItem[] = [
  { id: 1, title: 'Designing for a changing planet', category: 'Talks', date: 'Today, 4:00 PM', venue: 'The Forum', host: 'School of Design', attendees: 188, image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1000&q=80' },
  { id: 2, title: 'Spring student showcase', category: 'Exhibitions', date: 'Tomorrow, 6:30 PM', venue: 'Arts Quad', host: 'Student Arts Council', attendees: 347, image: 'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=1000&q=80' },
  { id: 3, title: 'Intramural finals: basketball', category: 'Sports', date: 'Thu, Apr 24, 7:00 PM', venue: 'Recreation Center', host: 'Campus Recreation', attendees: 96, image: 'https://images.unsplash.com/photo-1518407613690-d9fc990e795f?auto=format&fit=crop&w=1000&q=80' },
  { id: 4, title: 'Climate futures lab', category: 'Workshops', date: 'Fri, Apr 25, 12:00 PM', venue: 'Innovation Hub 02', host: 'Institute for Sustainability', attendees: 42, image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=1000&q=80' },
]
const navItems = [['◈', 'Overview'], ['▦', 'Discover'], ['◷', 'My registrations'], ['♢', 'Saved events']]
const modules = ['Overview', 'Discover', 'My registrations', 'Saved events', 'Create an event', 'Insights', 'Account info']

function moduleFromHash() { const value = decodeURIComponent(window.location.hash.slice(1)); return modules.includes(value) ? value : 'Overview' }

function App() {
  const [activeNav, setActiveNav] = useState(moduleFromHash)
  const [events, setEvents] = useState(seedEvents)
  const [registered, setRegistered] = useState<number[]>([2])
  const [saved, setSaved] = useState<number[]>([])
  const [query, setQuery] = useState('')
  const [activeFilter, setActiveFilter] = useState('All events')
  const [toast, setToast] = useState('')
  const [account, setAccount] = useState({ name: 'Alex Morgan', email: 'alex.morgan@campus.edu', department: 'Engineering', role: 'Student', reminders: true, announcements: true })
  useEffect(() => { const syncModule = () => setActiveNav(moduleFromHash()); window.addEventListener('hashchange', syncModule); window.addEventListener('popstate', syncModule); return () => { window.removeEventListener('hashchange', syncModule); window.removeEventListener('popstate', syncModule) } }, [])
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2500) }
  const filteredEvents = useMemo(() => events.filter((event) => `${event.title} ${event.category} ${event.venue} ${event.host}`.toLowerCase().includes(query.toLowerCase()) && (activeFilter === 'All events' || event.category === activeFilter)), [activeFilter, events, query])
  const toggleRegistration = (event: EventItem) => { setRegistered((current) => current.includes(event.id) ? current.filter((id) => id !== event.id) : [...current, event.id]); notify(registered.includes(event.id) ? `Registration cancelled for ${event.title}` : `Registered for ${event.title}`) }
  const toggleSaved = (event: EventItem) => { setSaved((current) => current.includes(event.id) ? current.filter((id) => id !== event.id) : [...current, event.id]); notify(saved.includes(event.id) ? 'Removed from saved events' : 'Event saved') }
  const openModule = (label: string) => { setActiveNav(label); setQuery(''); setActiveFilter('All events'); window.history.pushState({}, '', `#${encodeURIComponent(label)}`) }

  return <MotionConfig reducedMotion="user"><div className="app-shell sidebar-collapsed">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">✳</span><span>Campus events</span></div><div className="sidebar-label">Workspace</div><nav>{navItems.map(([icon, label]) => <button key={label} className={activeNav === label ? 'nav-item active' : 'nav-item'} onClick={() => openModule(label)}><span className="nav-icon">{icon}</span><span className="nav-label">{label}</span>{label === 'My registrations' && <span className="nav-count">{registered.length}</span>}</button>)}</nav><div className="sidebar-label lower-label">Manage</div><nav><button className={activeNav === 'Create an event' ? 'nav-item active' : 'nav-item'} onClick={() => openModule('Create an event')}><span className="nav-icon">＋</span><span className="nav-label">Create an event</span></button><button className={activeNav === 'Insights' ? 'nav-item active' : 'nav-item'} onClick={() => openModule('Insights')}><span className="nav-icon">↗</span><span className="nav-label">Insights</span></button></nav><div className="sidebar-bottom"><div className="help-card"><span className="help-icon">?</span><div><strong>Need a hand?</strong><span>Visit the help center</span></div><span>→</span></div><button className={activeNav === 'Account info' ? 'profile active' : 'profile'} onClick={() => openModule('Account info')}><span className="avatar">AM</span><span className="profile-copy"><strong>{account.name}</strong><small>{account.role} · {account.department}</small></span><span>⌄</span></button></div></aside>
    <main className="main-content"><header className="topbar"><div className="breadcrumb"><span>Workspace</span><span>/</span><strong>{activeNav}</strong></div><div className="top-actions"><button className="icon-button" aria-label="Notifications" onClick={() => notify('You have 3 new notifications.')}>♧<i></i></button><button className="user-avatar" aria-label="Open account info" onClick={() => openModule('Account info')}>{account.name.split(' ').map((part) => part[0]).join('')}</button></div></header><div className="content-wrap"><AnimatePresence mode="wait" initial={false}><motion.div className="module-transition" key={activeNav} initial={{ opacity: 0, y: 9 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -5 }} transition={{ duration: 0.18, ease: 'easeOut' }}>
      {activeNav === 'Overview' && <Overview events={events} registered={registered} saved={saved} onRegister={toggleRegistration} onSave={toggleSaved} onDiscover={() => openModule('Discover')} onCreate={() => openModule('Create an event')} />}
      {activeNav === 'Discover' && <EventBrowser title="Discover events" subtitle="Search the full campus calendar." events={filteredEvents} query={query} setQuery={setQuery} activeFilter={activeFilter} setActiveFilter={setActiveFilter} registered={registered} saved={saved} onRegister={toggleRegistration} onSave={toggleSaved} />}
      {activeNav === 'My registrations' && <EventBrowser title="My registrations" subtitle="Your confirmed and upcoming campus events." events={events.filter((event) => registered.includes(event.id))} query={query} setQuery={setQuery} activeFilter="All events" setActiveFilter={setActiveFilter} registered={registered} saved={saved} onRegister={toggleRegistration} onSave={toggleSaved} />}
      {activeNav === 'Saved events' && <EventBrowser title="Saved events" subtitle="Events you want to come back to." events={events.filter((event) => saved.includes(event.id))} query={query} setQuery={setQuery} activeFilter="All events" setActiveFilter={setActiveFilter} registered={registered} saved={saved} onRegister={toggleRegistration} onSave={toggleSaved} />}
      {activeNav === 'Create an event' && <CreateEvent onCreate={(event) => { setEvents((current) => [...current, event]); notify('Event submitted for admin approval'); openModule('Discover') }} />}
      {activeNav === 'Insights' && <Insights events={events} registered={registered} saved={saved} />}
      {activeNav === 'Account info' && <AccountInfo account={account} onSave={(nextAccount) => { setAccount(nextAccount); notify('Account information updated') }} />}
    </motion.div></AnimatePresence></div></main><AnimatePresence>{toast && <motion.div className="toast" role="status" initial={{ opacity: 0, y: 12, scale: 0.98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 8, scale: 0.98 }} transition={{ duration: 0.18, ease: 'easeOut' }}>{toast}<button onClick={() => setToast('')}>×</button></motion.div>}</AnimatePresence>
  </div></MotionConfig>
}

function Overview({ events, registered, saved, onRegister, onSave, onDiscover, onCreate }: { events: EventItem[]; registered: number[]; saved: number[]; onRegister: (event: EventItem) => void; onSave: (event: EventItem) => void; onDiscover: () => void; onCreate: () => void }) {
  return <><section className="welcome-row"><div><p className="eyebrow">Wednesday, April 23, 2025</p><h1>Good morning, Alex</h1><p className="welcome-copy">Find events, register, and keep your campus schedule in one place.</p></div><button className="primary-button" onClick={onCreate}><span>＋</span> Create an event</button></section><section className="hero-banner"><div className="hero-copy"><span className="tag">Featured event</span><h2>Designing for a changing planet</h2><p>Today · 4:00 PM · The Forum</p><button className="text-button" onClick={onDiscover}>View all events <span>↗</span></button></div><div className="hero-stat"><strong>24</strong><span>events this week</span></div></section><section className="stats-row"><div className="stat-card"><div className="stat-icon green">◷</div><div><span>My upcoming</span><strong>{String(registered.length).padStart(2, '0')} <small>events</small></strong></div></div><div className="stat-card"><div className="stat-icon yellow">♢</div><div><span>Saved events</span><strong>{String(saved.length).padStart(2, '0')} <small>to revisit</small></strong></div></div><div className="stat-card"><div className="stat-icon blue">✦</div><div><span>Campus events</span><strong>{events.length} <small>published</small></strong></div></div></section><section className="section-heading"><div><h2>Happening around campus</h2><p>Discover something worth showing up for.</p></div><button className="view-link" onClick={onDiscover}>View all events <span>↗</span></button></section><EventGrid events={events.slice(0, 3)} registered={registered} saved={saved} onRegister={onRegister} onSave={onSave} /></>
}

function EventBrowser({ title, subtitle, events, query, setQuery, activeFilter, setActiveFilter, registered, saved, onRegister, onSave }: { title: string; subtitle: string; events: EventItem[]; query: string; setQuery: (value: string) => void; activeFilter: string; setActiveFilter: (value: string) => void; registered: number[]; saved: number[]; onRegister: (event: EventItem) => void; onSave: (event: EventItem) => void }) {
  return <><section className="welcome-row"><div><p className="eyebrow">Campus calendar</p><h1>{title}</h1><p className="welcome-copy">{subtitle}</p></div></section><div className="toolbar"><div className="search-box"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search events, people, places..." /></div><div className="filter-group">{['All events', 'Talks', 'Workshops', 'Sports'].map((filter) => <button key={filter} className={activeFilter === filter ? 'filter active' : 'filter'} onClick={() => setActiveFilter(filter)}>{filter}</button>)}</div></div>{events.length ? <EventGrid events={events} registered={registered} saved={saved} onRegister={onRegister} onSave={onSave} /> : <div className="empty-state">No events here yet.</div>}</>
}

function EventGrid({ events, registered, saved, onRegister, onSave }: { events: EventItem[]; registered: number[]; saved: number[]; onRegister: (event: EventItem) => void; onSave: (event: EventItem) => void }) { return <motion.section className="event-grid" initial="hidden" animate="visible" variants={{ hidden: {}, visible: { transition: { staggerChildren: 0.055 } } }}>{events.map((event) => <motion.article className="event-card" key={event.id} variants={{ hidden: { opacity: 0, y: 12 }, visible: { opacity: 1, y: 0, transition: { duration: 0.24, ease: 'easeOut' } } }} whileHover={{ y: -4 }} whileTap={{ scale: 0.99 }}><div className="event-image" style={{ backgroundImage: `url(${event.image})` }}><span className="category-pill">{event.category}</span><button className={saved.includes(event.id) ? 'save-button saved' : 'save-button'} onClick={() => onSave(event)}>{saved.includes(event.id) ? '♥' : '♡'}</button></div><div className="event-info"><div className="event-date">{event.date}</div><h3>{event.title}</h3><div className="event-meta"><span>⌖ {event.venue}</span><span>◉ {event.host}</span></div><div className="event-footer"><div className="attendee-row"><span className="mini-avatar avatar-a">JL</span><span className="mini-avatar avatar-b">SK</span><span className="mini-avatar avatar-c">+{event.attendees - 2}</span></div><button className={registered.includes(event.id) ? 'register registered' : 'register'} onClick={() => onRegister(event)}>{registered.includes(event.id) ? 'Registered ✓' : 'Register'}</button></div></div></motion.article>)}</motion.section> }

function CreateEvent({ onCreate }: { onCreate: (event: EventItem) => void }) { const [title, setTitle] = useState(''); const [category, setCategory] = useState('Talks'); const [date, setDate] = useState(''); const [venue, setVenue] = useState(''); const submit = (event: FormEvent) => { event.preventDefault(); if (!title || !date || !venue) return; onCreate({ id: Date.now(), title, category, date, venue, host: 'Alex Morgan', attendees: 0, image: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1000&q=80' }) }; return <><section className="welcome-row"><div><p className="eyebrow">Organizer tools</p><h1>Create an event</h1><p className="welcome-copy">Submit a new event for admin approval and campus publishing.</p></div></section><form className="event-form" onSubmit={submit}><label>Event title<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. Robotics club open lab" required /></label><div className="form-row"><label>Category<select value={category} onChange={(event) => setCategory(event.target.value)}><option>Talks</option><option>Workshops</option><option>Sports</option><option>Exhibitions</option></select></label><label>Date and time<input value={date} onChange={(event) => setDate(event.target.value)} placeholder="Fri, Apr 25, 5:00 PM" required /></label></div><label>Venue<input value={venue} onChange={(event) => setVenue(event.target.value)} placeholder="Building or room" required /></label><label>Description<textarea placeholder="What should attendees know?" rows={5}></textarea></label><button className="primary-button" type="submit">Submit for approval</button></form></> }

function Insights({ events, registered, saved }: { events: EventItem[]; registered: number[]; saved: number[] }) { const totalAttendees = events.reduce((sum, event) => sum + event.attendees, 0); return <><section className="welcome-row"><div><p className="eyebrow">Workspace analytics</p><h1>Insights</h1><p className="welcome-copy">A quick view of event activity across campus.</p></div></section><section className="stats-row"><div className="stat-card"><div className="stat-icon green">◉</div><div><span>Published events</span><strong>{events.length}</strong></div></div><div className="stat-card"><div className="stat-icon yellow">♧</div><div><span>Total attendance</span><strong>{totalAttendees}</strong></div></div><div className="stat-card"><div className="stat-icon blue">◷</div><div><span>Your activity</span><strong>{registered.length + saved.length}</strong></div></div></section><div className="insight-panel"><h2>Event performance</h2>{events.map((event) => <div className="insight-row" key={event.id}><span>{event.title}</span><div className="progress"><i style={{ width: `${Math.min(100, event.attendees / 5)}%` }}></i></div><strong>{event.attendees}</strong></div>)}</div></> }

function AccountInfo({ account, onSave }: { account: Account; onSave: (account: Account) => void }) {
  const [draft, setDraft] = useState(account)
  const update = (field: keyof typeof draft, value: string | boolean) => setDraft((current) => ({ ...current, [field]: value }))
  return <><section className="welcome-row"><div><p className="eyebrow">Personal settings</p><h1>Account info</h1><p className="welcome-copy">Manage your profile and the notifications you receive.</p></div></section><form className="account-layout" onSubmit={(event) => { event.preventDefault(); onSave(draft) }}><div className="account-form"><div className="account-header"><span className="large-avatar">AM</span><div><strong>{draft.name}</strong><span>{draft.role} · {draft.department}</span></div></div><div className="form-row"><label>Full name<input value={draft.name} onChange={(event) => update('name', event.target.value)} required /></label><label>Email address<input type="email" value={draft.email} onChange={(event) => update('email', event.target.value)} required /></label></div><div className="form-row"><label>Department<select value={draft.department} onChange={(event) => update('department', event.target.value)}><option>Engineering</option><option>Arts and Design</option><option>Business</option><option>Sciences</option></select></label><label>Role<input value={draft.role} readOnly /></label></div><button className="primary-button" type="submit">Save changes</button></div><div className="preference-panel"><h2>Notifications</h2><p>Choose what you want to hear about.</p><label className="toggle-row"><span><strong>Event reminders</strong><small>Get a reminder before registered events.</small></span><input type="checkbox" checked={draft.reminders} onChange={(event) => update('reminders', event.target.checked)} /></label><label className="toggle-row"><span><strong>Campus announcements</strong><small>Receive important venue and schedule updates.</small></span><input type="checkbox" checked={draft.announcements} onChange={(event) => update('announcements', event.target.checked)} /></label></div></form></>
}

export default App
